gateway_callsign: MSHT-GW
gateway_uid: GW-01
# Einzelner Port:
meshtastic_port: COM7
# Mehrere Ports (Liste für Multi-Stream-Betrieb):
# meshtastic_port:
#   - COM7
#   - COM3
# Hier die IP deines Ubuntu-Servers eintragen "123.12.12.12"
tak_server_host: 123.12.12.12
# WICHTIG: Port 8088 nutzen (das ist der Eingang unserer Bridge)
tak_server_port: 8088

tak_server_protocol: TCP                               

# false = nur Nodes mit gültigen GPS-Koordinaten senden
# true  = Nodes ohne GPS-Fix ebenfalls senden (Fallback park_lat/park_lon)
send_nodes_without_gps: false
